version: "3.8"

services:
  mongo:
    container_name: mongodb
    image: mongo:5.0.18
    restart: always
    environment:
      TZ: "${TZ}"
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./mongodata:/data/db
    ports:
      - "${MONGO_EXT_PORT}:27017"

  backend:
    container_name: nodesv
    restart: always
    build: ./api-ag
    env_file:
      - ./api-ag/.env
    ports:
      - "3001:3001"
    links:
      - mongo
    depends_on:
      - mongo

  minio:
    image: quay.io/minio/minio
    container_name: minio1
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MONGO_USERNAME}
      MINIO_ROOT_PASSWORD: ${MONGO_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - ./miniodata:/data
