export const createContentAdapter = (content) => ({
  title: content.title,
  description: content.description,
  categorys: content.categorys,
  videoUrl: content.videoUrl,
  coverUrl: content.coverUrl,
  price: content.price,
  date: content.createdAt,
  id: content._id || content.id,
  status: content.state || content.status,
  trailer: content.trailer,
  priceTable: content.priceTable,
  likes: content.likes,
  dislikes: content.dislikes,
  views: content.cantVisits,
  liked: content.liked,
  disliked: content.disliked,
  favorite: content.favorite,
});
