const countries = [
  { label: "Afghanistan", id: "AFN" },
  { label: "Albania", id: "ALL" },
  { label: "Algeria", id: "DZD" },
  { label: "Andorra", id: "EUR" },
  { label: "Angola", id: "AOA" },
  { label: "Antigua and Barbuda", id: "XCD" },
  { label: "Argentina", id: "ARS" },
  { label: "Armenia", id: "AMD" },
  { label: "Australia", id: "AUD" },
  { label: "Austria", id: "EUR" },
  { label: "Azerbaijan", id: "AZN" },
  { label: "Bahamas", id: "BSD" },
  { label: "Bahrain", id: "BHD" },
  { label: "Bangladesh", id: "BDT" },
  { label: "Barbados", id: "BBD" },
  { label: "Belarus", id: "BYN" },
  { label: "Belgium", id: "EUR" },
  { label: "Belize", id: "BZD" },
  { label: "Benin", id: "XOF" },
  { label: "Bhutan", id: "BTN" },
  { label: "Bolivia", id: "BOB" },
  { label: "Bosnia and Herzegovina", id: "BAM" },
  { label: "Botswana", id: "BWP" },
  { label: "Brazil", id: "BRL" },
  { label: "Brunei", id: "BND" },
  { label: "Bulgaria", id: "BGN" },
  { label: "Burkina Faso", id: "XOF" },
  { label: "Burundi", id: "BIF" },
  { label: "Cabo Verde", id: "CVE" },
  { label: "Cambodia", id: "KHR" },
  { label: "Cameroon", id: "XAF" },
  { label: "Canada", id: "CAD" },
  { label: "Central African Republic", id: "XAF" },
  { label: "Chad", id: "XAF" },
  { label: "Chile", id: "CLP" },
  { label: "China", id: "CNY" },
  { label: "Colombia", id: "COL" },
  { label: "Comoros", id: "KMF" },
  { label: "Congo, Democratic Republic of the", id: "CDF" },
  { label: "Congo, Republic of the", id: "XAF" },
  { label: "Costa Rica", id: "CRC" },
  { label: "Croatia", id: "HRK" },
  { label: "Cuba", id: "CUP" },
  { label: "Cyprus", id: "EUR" },
  { label: "Czech Republic", id: "CZK" },
  { label: "Denmark", id: "DKK" },
  { label: "Djibouti", id: "DJF" },
  { label: "Dominica", id: "XCD" },
  { label: "Dominican Republic", id: "DOP" },
  { label: "Ecuador", id: "USD" },
  { label: "Egypt", id: "EGP" },
  { label: "El Salvador", id: "USD" },
  { label: "Equatorial Guinea", id: "XAF" },
  { label: "Eritrea", id: "ERN" },
  { label: "Estonia", id: "EUR" },
  { label: "Eswatini", id: "SZL" },
  { label: "Ethiopia", id: "ETB" },
  { label: "Fiji", id: "FJD" },
  { label: "Finland", id: "EUR" },
  { label: "France", id: "EUR" },
  { label: "Gabon", id: "XAF" },
  { label: "Gambia", id: "GMD" },
  { label: "Georgia", id: "GEL" },
  { label: "Germany", id: "EUR" },
  { label: "Ghana", id: "GHS" },
  { label: "Greece", id: "EUR" },
  { label: "Grenada", id: "XCD" },
  { label: "Guatemala", id: "GTQ" },
  { label: "Guinea", id: "GNF" },
  { label: "Guinea-Bissau", id: "XOF" },
  { label: "Guyana", id: "GYD" },
  { label: "Haiti", id: "HTG" },
  { label: "Honduras", id: "HNL" },
  { label: "Hungary", id: "HUF" },
  { label: "Iceland", id: "ISK" },
  { label: "India", id: "INR" },
  { label: "Indonesia", id: "IDR" },
  { label: "Iran", id: "IRR" },
  { label: "Iraq", id: "IQD" },
  { label: "Ireland", id: "EUR" },
  { label: "Israel", id: "ILS" },
  { label: "Italy", id: "EUR" },
  { label: "Jamaica", id: "JMD" },
  { label: "Japan", id: "JPY" },
  { label: "Jordan", id: "JOD" },
  { label: "Kazakhstan", id: "KZT" },
  { label: "Kenya", id: "KES" },
  { label: "Kiribati", id: "AUD" },
  { label: "Korea, North", id: "KPW" },
  { label: "Korea, South", id: "KRW" },
  { label: "Kuwait", id: "KWD" },
  { label: "Kyrgyzstan", id: "KGS" },
  { label: "Laos", id: "LAK" },
  { label: "Latvia", id: "EUR" },
  { label: "Lebanon", id: "LBP" },
  { label: "Lesotho", id: "LSL" },
  { label: "Liberia", id: "LRD" },
  { label: "Libya", id: "LYD" },
  { label: "Liechtenstein", id: "CHF" },
  { label: "Lithuania", id: "EUR" },
  { label: "Luxembourg", id: "EUR" },
  { label: "Madagascar", id: "MGA" },
  { label: "Malawi", id: "MWK" },
  { label: "Malaysia", id: "MYR" },
  { label: "Maldives", id: "MVR" },
  { label: "Mali", id: "XOF" },
  { label: "Malta", id: "EUR" },
  { label: "Marshall Islands", id: "USD" },
  { label: "Mauritania", id: "MRU" },
  { label: "Mauritius", id: "MUR" },
  { label: "Mexico", id: "MXN" },
  { label: "Micronesia", id: "USD" },
  { label: "Moldova", id: "MDL" },
  { label: "Monaco", id: "EUR" },
  { label: "Mongolia", id: "MNT" },
  { label: "Montenegro", id: "EUR" },
  { label: "Morocco", id: "MAD" },
  { label: "Mozambique", id: "MZN" },
  { label: "Myanmar", id: "MMK" },
  { label: "Namibia", id: "NAD" },
  { label: "Nauru", id: "AUD" },
  { label: "Nepal", id: "NPR" },
  { label: "Netherlands", id: "EUR" },
  { label: "New Zealand", id: "NZD" },
  { label: "Nicaragua", id: "NIO" },
  { label: "Niger", id: "XOF" },
  { label: "Nigeria", id: "NGN" },
  { label: "North Macedonia", id: "MKD" },
  { label: "Norway", id: "NOK" },
  { label: "Oman", id: "OMR" },
  { label: "Pakistan", id: "PKR" },
  { label: "Palau", id: "USD" },
  { label: "Palestine", id: "ILS" },
  { label: "Panama", id: "PAB" },
  { label: "Papua New Guinea", id: "PGK" },
  { label: "Paraguay", id: "PYG" },
  { label: "Peru", id: "PEN" },
  { label: "Philippines", id: "PHP" },
  { label: "Poland", id: "PLN" },
  { label: "Portugal", id: "EUR" },
  { label: "Qatar", id: "QAR" },
  { label: "Romania", id: "RON" },
  { label: "Russia", id: "RUB" },
  { label: "Rwanda", id: "RWF" },
  { label: "Saint Kitts and Nevis", id: "XCD" },
  { label: "Saint Lucia", id: "XCD" },
  { label: "Saint Vincent and the Grenadines", id: "XCD" },
  { label: "Samoa", id: "WST" },
  { label: "San Marino", id: "EUR" },
  { label: "Sao Tome and Principe", id: "STN" },
  { label: "Saudi Arabia", id: "SAR" },
  { label: "Senegal", id: "XOF" },
  { label: "Serbia", id: "RSD" },
  { label: "Seychelles", id: "SCR" },
  { label: "Sierra Leone", id: "SLL" },
  { label: "Singapore", id: "SGD" },
  { label: "Slovakia", id: "EUR" },
  { label: "Slovenia", id: "EUR" },
  { label: "Solomon Islands", id: "SBD" },
  { label: "Somalia", id: "SOS" },
  { label: "South Africa", id: "ZAR" },
  { label: "South Sudan", id: "SSP" },
  { label: "Spain", id: "EUR" },
  { label: "Sri Lanka", id: "LKR" },
  { label: "Sudan", id: "SDG" },
  { label: "Surilabel", id: "SRD" },
  { label: "Sweden", id: "SEK" },
  { label: "Switzerland", id: "CHF" },
  { label: "Syria", id: "SYP" },
  { label: "Taiwan", id: "TWD" },
  { label: "Tajikistan", id: "TJS" },
  { label: "Tanzania", id: "TZS" },
  { label: "Thailand", id: "THB" },
  { label: "Timor-Leste", id: "USD" },
  { label: "Togo", id: "XOF" },
  { label: "Tonga", id: "TOP" },
  { label: "Trinidad and Tobago", id: "TTD" },
  { label: "Tunisia", id: "TND" },
  { label: "Turkey", id: "TRY" },
  { label: "Turkmenistan", id: "TMT" },
  { label: "Tuvalu", id: "AUD" },
  { label: "Uganda", id: "UGX" },
  { label: "Ukraine", id: "UAH" },
  { label: "United Arab Emirates", id: "AED" },
  { label: "United Kingdom", id: "GBP" },
  { label: "United States", id: "USD" },
  { label: "Uruguay", id: "UYU" },
  { label: "Uzbekistan", id: "UZS" },
  { label: "Vanuatu", id: "VUV" },
  { label: "Vatican City", id: "EUR" },
  { label: "Venezuela", id: "VES" },
  { label: "Vietnam", id: "VND" },
  { label: "Yemen", id: "YER" },
  { label: "Zambia", id: "ZMW" },
  { label: "Zimbabwe", id: "ZWL" },
];

export default countries;
