name: Deploy App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d_%H:%M:%S')" >> $GITHUB_OUTPUT

      - name: Pull latest changes from the repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "xaveeg@gmail.com"
          git config --global user.name "BDKX16"
          git remote set-url origin https://BDKX16:${{ secrets.GITHUB_TOKEN }}@github.com/BDKX16/Projecto-OF.git
          git pull origin main

      - name: "Deploy to server"
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /srv/repositories/Projecto-OF/projecto-ag
            git pull
            npm run build
            rm -r /var/www/almendragala.com/html
            mkdir /var/www/almendragala.com/html
            cp -r dist/ /var/www/almendragala.com/html
            cd /var/www/almendragala.com/html
            cp -r /var/www/almendragala.com/html/dist/* .
            rm -r /var/www/almendragala.com/html/dist/

      - name: "Set up Docker Compose"
        uses: docker/compose-action@v2
        with:
          compose-file: docker-compose.yml
